<div class="notes-wrapper">
    <div id='infodiv'>
        <h2>Requirements</h2>
        <ul>
            <li>Package should be in 'zip' format.</li>
            <li>Either the content of Zip should be in format app/code/VendorName/ModuleName..</li>
            <li>Or the composer.json and other extension directories(Block,Controller,Model etc) should be at root of zip file.</li>
        </ul>
        <h2>Powered By <a href="https://moduleforest.com?utm_source=extension_installer" target="blank">ModuleForest</a>.  <a href="https://magento.moduleforest.com?utm_source=extension_installer" target="blank">Visit our store</a> for more extensions from different vendors.</h2>
    </div>
</div>